// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueerUni.Models;

#nullable disable

namespace QueerUni.Migrations
{
    [DbContext(typeof(QueerUniContext))]
    partial class QueerUniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QueerUni.Models.track", b =>
                {
                    b.Property<int>("trackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("trackName")
                        .HasColumnType("longtext");

                    b.Property<int>("trackNumber")
                        .HasColumnType("int");

                    b.HasKey("trackId");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("QueerUni.Models.CurrentTerm", b =>
                {
                    b.Property<int>("CurrentTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("trackId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CurrentTermId");

                    b.HasIndex("trackId");

                    b.HasIndex("StudentId");

                    b.ToTable("CurrentTerm");
                });

            modelBuilder.Entity("QueerUni.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("trackId")
                        .HasColumnType("int");

                    b.Property<int>("Major")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("trackId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("QueerUni.Models.CurrentTerm", b =>
                {
                    b.HasOne("QueerUni.Models.track", "tracks")
                        .WithMany("JoinEntities")
                        .HasForeignKey("trackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueerUni.Models.Student", "Student")
                        .WithMany("JoinEntities")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tracks");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QueerUni.Models.Student", b =>
                {
                    b.HasOne("QueerUni.Models.track", "track")
                        .WithMany("Students")
                        .HasForeignKey("trackId");

                    b.Navigation("track");
                });

            modelBuilder.Entity("QueerUni.Models.track", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("QueerUni.Models.Student", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
